[package]
name = "facto"
version = "0.1.0"
authors = ["David Terrell <dbt@meat.net>"]
edition = "2018"

[dependencies]
base64 = "0.13.0"
clap = "2.33.0"
flate2 = "1.0.20"
qrcode-generator="4.0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.59"
structopt = "0.3"